# Generated by Django 4.2.6 on 2023-10-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subsription",
        ),
    ]
