# Generated by Django 4.2.6 on 2023-10-19 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_delete_subsription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
        migrations.AddField(
            model_name="order",
            name="has_paid",
            field=models.BooleanField(default=False, verbose_name="Payment Status"),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 10, 19, 10, 29, 42, 260349, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
