# Generated by Django 4.2.6 on 2023-10-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_remove_order_paid_order_has_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="description",
        ),
    ]
